# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=25)),
                ('student_class', models.CharField(max_length=10)),
                ('student_hw_sub1', models.CharField(max_length=250)),
                ('student_hw_sub2', models.CharField(max_length=250)),
                ('student_hw_sub3', models.CharField(max_length=250)),
                ('student_hw_sub4', models.CharField(max_length=250)),
                ('student_hw_sub5', models.CharField(max_length=250)),
                ('student_hw_sub6', models.CharField(max_length=250)),
            ],
        ),
    ]
