# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-13 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='student_hw_sub1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student_hw_sub2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student_hw_sub3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student_hw_sub4',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student_hw_sub5',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student_hw_sub6',
            field=models.CharField(max_length=1000),
        ),
    ]
